# Dependabot configuration file
version: 2
updates:
  # Monitorar atualizações para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitorar atualizações para Python (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitorar atualizações para Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitorar atualizações para npm (se houver package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
