name: CI/CD DAG ASM
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y nasm
    - run: |
        nasm -f elf src/ASM/dag.asm -o dag.o
        ld -m elf_i386 -s -o dag dag.o
    - uses: actions/upload-artifact@v4
      with:
        name: dag-artifact
        path: dag
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        files: dag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
