name: CI/CD DAG ASM
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y nasm
    - run: |
        nasm -f elf src/ASM/dag.asm -o dag.o
        ld -m elf_i386 -s -o dag dag.o
    - uses: actions/upload-artifact@v4
      with:
        name: dag-artifact
        path: dag
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        files: dag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Tag and Release
      id: tag_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const date = new Date();
          const tag = `v${date.getUTCFullYear()}.${(date.getUTCMonth() + 1).toString().padStart(2, '0')}.${date.getUTCDate().toString().padStart(2, '0')}-run${context.runNumber}`;
          
          try {
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            });
            
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: `Release ${tag} - DAG CI/CD`,
              body: `Automated release from DAG CI/CD on commit ${context.sha}`,
              draft: false,
              prerelease: false
            });
          } catch (error) {
            console.log("Error creating tag or release: " + error);
          }
