name: Docker Image CI | CD Build conteiner and Deploy Environment 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker conteiner image 
      continue-on-error: false
        
      run: docker build . --file Dockerfile --tag edge-ai-from-cloud-sky-to-silicon-metal-prisioner-at-the-exoteric-hex-chip:$(date +%s)
