name: CI/CD PetriNet ASM
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y nasm
    - run: |
        nasm -f elf src/asm/petrinet.asm -o petrinet.o
        ld -m elf_i386 -s -o petrinet petrinet.o
    - uses: actions/upload-artifact@v4
      with:
        name: petrinet-artifact
        path: petrinet
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        files: petrinet
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
